brand:              /images/logo/logo_square.jpg
image:
og:
  image:            /images/main/main.jpg

url:                http//intsystems.github.io
edit:               https://github.com/intsystems/intsystems.github.io/edit/main/
baseurl:
permalink:          /:year/:month/:day/:title.html

sidebar: true

# Main Info
github: intsystems
mail: research.n.math@gmail.com
youtube: https://www.youtube.com/c/MachineLearningPhystech

header:
- Machine Learning
- Data Analysis

# Markdown
markdown:           kramdown

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

exclude: ["LICENSE", "README.md", "Gemfile", "Gemfile.lock", "vendor", "_sass"]

# Highlighter
highlighter:        rouge

plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - jekyll-toc
  - jekyll-sitemap

languages: ["en", "ru"]

exclude_from_localizations: ["images", "favicon.ico", "javascript", "style.scss"]

default_locale_in_subfolder: False

# Navigation
nav:
  pages:
  - id: "home"
    href: "/"
    name: site.nav.names.home
  - id: "education"
    href: "/education"
    name: site.nav.names.education
  - id: "about"
    href: "/about"
    name: site.nav.names.about
  - id: "lecturers"
    href: "/people"
    name: site.nav.names.lecturers
  - id: "courses"
    href: "/course"
    name: site.nav.names.courses
  - id: "admission"
    href: "/admission"
    name: site.nav.names.admission
  - id: "materials"
    href: "/materials"
    name: site.nav.names.materials
    dropdown:
    - id: "nir"
      href: "/materials/nir"
      name: site.nav.names.nir
    - id: "scholarship"
      href: "/materials/scholarship"
      name: site.nav.names.scholarship
    - id: "thesis"
      href: "/materials/thesis"
      name: site.nav.names.thesis
    - id: "seminars"
      href: "/materials/seminars"
      name: site.nav.names.seminars
    - id: "paper_guidelines"
      href: "/materials/paper_guidelines"
      name: site.nav.names.paper_guidelines

# Scopes
defaults:
  - scope:
      path: ""
    values:
      toc: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "materials"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "admission"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "people"
    values:
      layout: "profile"
  - scope:
      path: ""
      type: "course"
    values:
      layout: "course"

collections:
  people:
    output: true
    permalink: /people/:title/index.html
  course:
    output: true
    permalink: /course/:title/index.html


global:
  langs:
    ru: Русский
    en: English

  course:
    types:
    - bachelor
    - master
    - deprecated

  people:
    roles:
    - hotd
    - dos
    - phd
    - gs
    - template
