name: Build and deploy Jekyll site to GitHub Pages (IS)

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
          pre_build_commands: git config --global http.version HTTP/1.1; git config --global http.postBuffer 157286400; apk fetch git-lfs
